name: just_media_compare
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # State management
  flutter_riverpod: ^2.4.9
  # Audio packages
  just_audio: ^0.10.3
  media_kit: ^1.2.0
  media_kit_libs_audio: ^1.0.6
  audioplayers: ^6.4.0
  # Stream utilities
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/audio/
